config/routes.rb
Rails.application.routes.draw do

  resources :artists do 
    resources :songs 
  end

  root 'artists#index'

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :songs 
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :song
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :artist
  has_many :ratings 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def index
    @artists = Artist.all 
  end 

  def show
    @artist = Artist.find(params[:id])
    @songs = @artist.songs
  end 

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def show 
    @song = Song.find(params[:id])
  end 

  def new 
    @song = Song.new 
    @artist = Artist.find(params[:artist_id])
  end 

  def create 
    @song = Song.new(song_params)
    @song.artist_id = params[:artist_id]
    @song.save 
    redirect_to root_path 
  end 

  private 
  def song_params
    params.require(:song).permit(:title, :artist_id, :length, :optimal_volume)
  end 








end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/index.html.erb
<h2>Artists Index View!</h2>

<% @artists.each do |a| %> 
  <%= a.name %>
  <%= a.hometown %> 
<% end %> 

app/views/artists/show.html.erb
<h2>Artist Show Page</h2>

<%= @artist.name %> 

<ul>
<% @songs.each do |s| %>
  <li>
  <%= link_to s.title, artist_song_path(@artist.id, s.id) %> 
  </li>
<% end %> 
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bestestsong</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
<h1>Bestest Song App</h1>
</header>

<%= yield %>
<footer>
  <%= link_to "Home", root_path %> 
  <p>Copyright 2014 by Cheri</p>
</footer>

</body>
</html>

app/views/songs/new.html.erb
<h2>Suggest a New Song</h2>

<%= form_for [ @artist, @song ] do |f| %>

  <%= f.label :title %> 
  <%= f.text_field :title %> 

  <%= f.submit 'Submit' %> 

<% end %>

app/views/songs/show.html.erb
<h2>Show <%= @song.title %> </h2>

<p> <%= @song.length %> minutes of awesome! 
Best played at <%= @song.optimal_volume %>. 
</p>